# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tpximpactai-webapp-dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://tpximpactaicontainerreg.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f4311fd0a6a749d0b60c55e07dd85954 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_23854d71cb904bf6be9b33a5cfa8b08c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: tpximpactaicontainerreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f4311fd0a6a749d0b60c55e07dd85954 }}/tpximpactaicontainerreg/tpxwebappcontainerdev:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tpximpactai-webapp-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_60aecd3f01184ac4b8f1376ff7580db8 }}
        images: 'tpximpactaicontainerreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f4311fd0a6a749d0b60c55e07dd85954 }}/tpximpactaicontainerreg/tpxwebappcontainerdev:${{ github.sha }}'