name: Build and deploy container app to Azure Web App - tpximpactai-webapp-dev

on:
  push:
    branches:
      - workflow

jobs:
  build:
    runs-on: "ubuntu-latest"

    env:
      REGISTRY: sharedimpactaiacr.azurecr.io
      IMAGE_NAME: impactaidev
      AZURE_WEBAPP_NAME: tpximpactai-webapp-dev

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.AzureAppService_ContainerUsername_30d95bc31d7a4f7b94356110c32d0cf9 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_37acd21db4064784bc3335c9f4238807 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          file: ./WebApp.Dockerfile

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          slot-name: "dev"
